services:
  xiaoaitts:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 0.0.0.0:8848:8848
    env_file:
      - .env

networks:
  default:
    name: api